"""empty message

Revision ID: 08b79bd091f9
Revises: fa19ccadd2fc
Create Date: 2023-05-11 01:04:28.047742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b79bd091f9'
down_revision = 'fa19ccadd2fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous', sa.String(), nullable=True))

    with op.batch_alter_table('dispatch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch', schema=None) as batch_op:
        batch_op.drop_column('previous')

    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_column('previous')

    # ### end Alembic commands ###
