"""empty message

Revision ID: 20225170af92
Revises: 885489a69964
Create Date: 2023-05-12 09:23:06.667413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20225170af92'
down_revision = '885489a69964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_option', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_column('payment_option')

    # ### end Alembic commands ###
