"""empty message

Revision ID: 7f3c93bb8882
Revises: 6fafd2d968a0
Create Date: 2023-04-29 18:58:14.768515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3c93bb8882'
down_revision = '6fafd2d968a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stage', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch', schema=None) as batch_op:
        batch_op.drop_column('stage')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
