"""empty message

Revision ID: 885489a69964
Revises: aba72fb90442
Create Date: 2023-05-11 20:28:06.104823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885489a69964'
down_revision = 'aba72fb90442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_reference', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_column('payment_reference')

    # ### end Alembic commands ###
