"""empty message

Revision ID: aba72fb90442
Revises: b50bafdc14a5
Create Date: 2023-05-11 20:18:45.468911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba72fb90442'
down_revision = 'b50bafdc14a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fees', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('fees')

    # ### end Alembic commands ###
