"""empty message

Revision ID: bf19feb7cba9
Revises: b1f836ec2fcb
Create Date: 2023-05-12 17:20:21.384623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf19feb7cba9'
down_revision = 'b1f836ec2fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pickup_phone_number', sa.String(), nullable=True))
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('pickup_phone_number')
        batch_op.drop_column('pickup_name')

    # ### end Alembic commands ###
